<?php
/**
 * ImageDescriptionResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ImageDescriptionResponse Class Doc Comment
 *
 * @category Class
 * @description Result of recognizing an image
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ImageDescriptionResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ImageDescriptionResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'successful' => 'bool',
        'highconfidence' => 'bool',
        'best_outcome' => '\Swagger\Client\Model\RecognitionOutcome',
        'runner_up_outcome' => '\Swagger\Client\Model\RecognitionOutcome'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'successful' => null,
        'highconfidence' => null,
        'best_outcome' => null,
        'runner_up_outcome' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'successful' => 'Successful',
        'highconfidence' => 'Highconfidence',
        'best_outcome' => 'BestOutcome',
        'runner_up_outcome' => 'RunnerUpOutcome'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'successful' => 'setSuccessful',
        'highconfidence' => 'setHighconfidence',
        'best_outcome' => 'setBestOutcome',
        'runner_up_outcome' => 'setRunnerUpOutcome'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'successful' => 'getSuccessful',
        'highconfidence' => 'getHighconfidence',
        'best_outcome' => 'getBestOutcome',
        'runner_up_outcome' => 'getRunnerUpOutcome'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['successful'] = isset($data['successful']) ? $data['successful'] : null;
        $this->container['highconfidence'] = isset($data['highconfidence']) ? $data['highconfidence'] : null;
        $this->container['best_outcome'] = isset($data['best_outcome']) ? $data['best_outcome'] : null;
        $this->container['runner_up_outcome'] = isset($data['runner_up_outcome']) ? $data['runner_up_outcome'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets successful
     *
     * @return bool
     */
    public function getSuccessful()
    {
        return $this->container['successful'];
    }

    /**
     * Sets successful
     *
     * @param bool $successful Was the image processed successfully?
     *
     * @return $this
     */
    public function setSuccessful($successful)
    {
        $this->container['successful'] = $successful;

        return $this;
    }

    /**
     * Gets highconfidence
     *
     * @return bool
     */
    public function getHighconfidence()
    {
        return $this->container['highconfidence'];
    }

    /**
     * Sets highconfidence
     *
     * @param bool $highconfidence Is the resulting best outcome recognition a high confidence outcome?
     *
     * @return $this
     */
    public function setHighconfidence($highconfidence)
    {
        $this->container['highconfidence'] = $highconfidence;

        return $this;
    }

    /**
     * Gets best_outcome
     *
     * @return \Swagger\Client\Model\RecognitionOutcome
     */
    public function getBestOutcome()
    {
        return $this->container['best_outcome'];
    }

    /**
     * Sets best_outcome
     *
     * @param \Swagger\Client\Model\RecognitionOutcome $best_outcome The best Machine Learning outcome
     *
     * @return $this
     */
    public function setBestOutcome($best_outcome)
    {
        $this->container['best_outcome'] = $best_outcome;

        return $this;
    }

    /**
     * Gets runner_up_outcome
     *
     * @return \Swagger\Client\Model\RecognitionOutcome
     */
    public function getRunnerUpOutcome()
    {
        return $this->container['runner_up_outcome'];
    }

    /**
     * Sets runner_up_outcome
     *
     * @param \Swagger\Client\Model\RecognitionOutcome $runner_up_outcome Best backup (\"runner up\") Machine Learning outcome
     *
     * @return $this
     */
    public function setRunnerUpOutcome($runner_up_outcome)
    {
        $this->container['runner_up_outcome'] = $runner_up_outcome;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


