<?php
/**
 * NsfwAdvancedResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * NsfwAdvancedResult Class Doc Comment
 *
 * @category Class
 * @description Result of an Advanced NSFW classification
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NsfwAdvancedResult implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'NsfwAdvancedResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'successful' => 'bool',
        'clean_result' => 'bool',
        'contains_nudity' => 'bool',
        'contains_graphic_violence' => 'bool',
        'contains_non_graphic_violence' => 'bool',
        'contains_self_harm' => 'bool',
        'contains_hate' => 'bool',
        'contains_potential_illegal_activity' => 'bool',
        'contains_medical_imagery' => 'bool',
        'contains_profanity' => 'bool',
        'score' => 'double',
        'classification_outcome' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'successful' => null,
        'clean_result' => null,
        'contains_nudity' => null,
        'contains_graphic_violence' => null,
        'contains_non_graphic_violence' => null,
        'contains_self_harm' => null,
        'contains_hate' => null,
        'contains_potential_illegal_activity' => null,
        'contains_medical_imagery' => null,
        'contains_profanity' => null,
        'score' => 'double',
        'classification_outcome' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'successful' => 'Successful',
        'clean_result' => 'CleanResult',
        'contains_nudity' => 'ContainsNudity',
        'contains_graphic_violence' => 'ContainsGraphicViolence',
        'contains_non_graphic_violence' => 'ContainsNonGraphicViolence',
        'contains_self_harm' => 'ContainsSelfHarm',
        'contains_hate' => 'ContainsHate',
        'contains_potential_illegal_activity' => 'ContainsPotentialIllegalActivity',
        'contains_medical_imagery' => 'ContainsMedicalImagery',
        'contains_profanity' => 'ContainsProfanity',
        'score' => 'Score',
        'classification_outcome' => 'ClassificationOutcome'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'successful' => 'setSuccessful',
        'clean_result' => 'setCleanResult',
        'contains_nudity' => 'setContainsNudity',
        'contains_graphic_violence' => 'setContainsGraphicViolence',
        'contains_non_graphic_violence' => 'setContainsNonGraphicViolence',
        'contains_self_harm' => 'setContainsSelfHarm',
        'contains_hate' => 'setContainsHate',
        'contains_potential_illegal_activity' => 'setContainsPotentialIllegalActivity',
        'contains_medical_imagery' => 'setContainsMedicalImagery',
        'contains_profanity' => 'setContainsProfanity',
        'score' => 'setScore',
        'classification_outcome' => 'setClassificationOutcome'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'successful' => 'getSuccessful',
        'clean_result' => 'getCleanResult',
        'contains_nudity' => 'getContainsNudity',
        'contains_graphic_violence' => 'getContainsGraphicViolence',
        'contains_non_graphic_violence' => 'getContainsNonGraphicViolence',
        'contains_self_harm' => 'getContainsSelfHarm',
        'contains_hate' => 'getContainsHate',
        'contains_potential_illegal_activity' => 'getContainsPotentialIllegalActivity',
        'contains_medical_imagery' => 'getContainsMedicalImagery',
        'contains_profanity' => 'getContainsProfanity',
        'score' => 'getScore',
        'classification_outcome' => 'getClassificationOutcome'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['successful'] = isset($data['successful']) ? $data['successful'] : null;
        $this->container['clean_result'] = isset($data['clean_result']) ? $data['clean_result'] : null;
        $this->container['contains_nudity'] = isset($data['contains_nudity']) ? $data['contains_nudity'] : null;
        $this->container['contains_graphic_violence'] = isset($data['contains_graphic_violence']) ? $data['contains_graphic_violence'] : null;
        $this->container['contains_non_graphic_violence'] = isset($data['contains_non_graphic_violence']) ? $data['contains_non_graphic_violence'] : null;
        $this->container['contains_self_harm'] = isset($data['contains_self_harm']) ? $data['contains_self_harm'] : null;
        $this->container['contains_hate'] = isset($data['contains_hate']) ? $data['contains_hate'] : null;
        $this->container['contains_potential_illegal_activity'] = isset($data['contains_potential_illegal_activity']) ? $data['contains_potential_illegal_activity'] : null;
        $this->container['contains_medical_imagery'] = isset($data['contains_medical_imagery']) ? $data['contains_medical_imagery'] : null;
        $this->container['contains_profanity'] = isset($data['contains_profanity']) ? $data['contains_profanity'] : null;
        $this->container['score'] = isset($data['score']) ? $data['score'] : null;
        $this->container['classification_outcome'] = isset($data['classification_outcome']) ? $data['classification_outcome'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets successful
     *
     * @return bool
     */
    public function getSuccessful()
    {
        return $this->container['successful'];
    }

    /**
     * Sets successful
     *
     * @param bool $successful True if the classification was successfully run, false otherwise
     *
     * @return $this
     */
    public function setSuccessful($successful)
    {
        $this->container['successful'] = $successful;

        return $this;
    }

    /**
     * Gets clean_result
     *
     * @return bool
     */
    public function getCleanResult()
    {
        return $this->container['clean_result'];
    }

    /**
     * Sets clean_result
     *
     * @param bool $clean_result True if the result was clean, false otherwise
     *
     * @return $this
     */
    public function setCleanResult($clean_result)
    {
        $this->container['clean_result'] = $clean_result;

        return $this;
    }

    /**
     * Gets contains_nudity
     *
     * @return bool
     */
    public function getContainsNudity()
    {
        return $this->container['contains_nudity'];
    }

    /**
     * Sets contains_nudity
     *
     * @param bool $contains_nudity True if the image contains nudity or sex, false otherwise
     *
     * @return $this
     */
    public function setContainsNudity($contains_nudity)
    {
        $this->container['contains_nudity'] = $contains_nudity;

        return $this;
    }

    /**
     * Gets contains_graphic_violence
     *
     * @return bool
     */
    public function getContainsGraphicViolence()
    {
        return $this->container['contains_graphic_violence'];
    }

    /**
     * Sets contains_graphic_violence
     *
     * @param bool $contains_graphic_violence True if the image contains graphic violence and/or gore, false otherwise
     *
     * @return $this
     */
    public function setContainsGraphicViolence($contains_graphic_violence)
    {
        $this->container['contains_graphic_violence'] = $contains_graphic_violence;

        return $this;
    }

    /**
     * Gets contains_non_graphic_violence
     *
     * @return bool
     */
    public function getContainsNonGraphicViolence()
    {
        return $this->container['contains_non_graphic_violence'];
    }

    /**
     * Sets contains_non_graphic_violence
     *
     * @param bool $contains_non_graphic_violence True if the image contains non-graphic violence, e.g. weapons, false otherwise
     *
     * @return $this
     */
    public function setContainsNonGraphicViolence($contains_non_graphic_violence)
    {
        $this->container['contains_non_graphic_violence'] = $contains_non_graphic_violence;

        return $this;
    }

    /**
     * Gets contains_self_harm
     *
     * @return bool
     */
    public function getContainsSelfHarm()
    {
        return $this->container['contains_self_harm'];
    }

    /**
     * Sets contains_self_harm
     *
     * @param bool $contains_self_harm True if the image contains self-harm or suicide imagery, false otherwise
     *
     * @return $this
     */
    public function setContainsSelfHarm($contains_self_harm)
    {
        $this->container['contains_self_harm'] = $contains_self_harm;

        return $this;
    }

    /**
     * Gets contains_hate
     *
     * @return bool
     */
    public function getContainsHate()
    {
        return $this->container['contains_hate'];
    }

    /**
     * Sets contains_hate
     *
     * @param bool $contains_hate True if the image contains hate, false otherwise
     *
     * @return $this
     */
    public function setContainsHate($contains_hate)
    {
        $this->container['contains_hate'] = $contains_hate;

        return $this;
    }

    /**
     * Gets contains_potential_illegal_activity
     *
     * @return bool
     */
    public function getContainsPotentialIllegalActivity()
    {
        return $this->container['contains_potential_illegal_activity'];
    }

    /**
     * Sets contains_potential_illegal_activity
     *
     * @param bool $contains_potential_illegal_activity True if the image contains potentially illegal activity such as drugs, false otherwise
     *
     * @return $this
     */
    public function setContainsPotentialIllegalActivity($contains_potential_illegal_activity)
    {
        $this->container['contains_potential_illegal_activity'] = $contains_potential_illegal_activity;

        return $this;
    }

    /**
     * Gets contains_medical_imagery
     *
     * @return bool
     */
    public function getContainsMedicalImagery()
    {
        return $this->container['contains_medical_imagery'];
    }

    /**
     * Sets contains_medical_imagery
     *
     * @param bool $contains_medical_imagery True if the image contains medical imagery, false otherwise
     *
     * @return $this
     */
    public function setContainsMedicalImagery($contains_medical_imagery)
    {
        $this->container['contains_medical_imagery'] = $contains_medical_imagery;

        return $this;
    }

    /**
     * Gets contains_profanity
     *
     * @return bool
     */
    public function getContainsProfanity()
    {
        return $this->container['contains_profanity'];
    }

    /**
     * Sets contains_profanity
     *
     * @param bool $contains_profanity True if the image contains profanity or obscenities, false otherwise
     *
     * @return $this
     */
    public function setContainsProfanity($contains_profanity)
    {
        $this->container['contains_profanity'] = $contains_profanity;

        return $this;
    }

    /**
     * Gets score
     *
     * @return double
     */
    public function getScore()
    {
        return $this->container['score'];
    }

    /**
     * Sets score
     *
     * @param double $score Score between 0.0 and 1.0.  Scores of 0.0-0.2 represent high probability safe content, while scores 0.8-1.0 represent high probability unsafe content.  Content between 0.2 and 0.8 is of increasing raciness.
     *
     * @return $this
     */
    public function setScore($score)
    {
        $this->container['score'] = $score;

        return $this;
    }

    /**
     * Gets classification_outcome
     *
     * @return string
     */
    public function getClassificationOutcome()
    {
        return $this->container['classification_outcome'];
    }

    /**
     * Sets classification_outcome
     *
     * @param string $classification_outcome Classification result into four categories: SafeContent_HighProbability, UnsafeContent_HighProbability, RacyContent, SafeContent_ModerateProbability
     *
     * @return $this
     */
    public function setClassificationOutcome($classification_outcome)
    {
        $this->container['classification_outcome'] = $classification_outcome;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


