<?php
/**
 * PersonWithAge
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PersonWithAge Class Doc Comment
 *
 * @category Class
 * @description A person identified in an image age classification operation
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PersonWithAge implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PersonWithAge';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'face_location' => '\Swagger\Client\Model\Face',
        'age_classification_confidence' => 'double',
        'age_class' => 'string',
        'age' => 'double',
        'gender_classification' => 'string',
        'gender_female_confidence' => 'double',
        'gender_male_confidence' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'face_location' => null,
        'age_classification_confidence' => 'double',
        'age_class' => null,
        'age' => 'double',
        'gender_classification' => null,
        'gender_female_confidence' => 'double',
        'gender_male_confidence' => 'double'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'face_location' => 'FaceLocation',
        'age_classification_confidence' => 'AgeClassificationConfidence',
        'age_class' => 'AgeClass',
        'age' => 'Age',
        'gender_classification' => 'GenderClassification',
        'gender_female_confidence' => 'GenderFemaleConfidence',
        'gender_male_confidence' => 'GenderMaleConfidence'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'face_location' => 'setFaceLocation',
        'age_classification_confidence' => 'setAgeClassificationConfidence',
        'age_class' => 'setAgeClass',
        'age' => 'setAge',
        'gender_classification' => 'setGenderClassification',
        'gender_female_confidence' => 'setGenderFemaleConfidence',
        'gender_male_confidence' => 'setGenderMaleConfidence'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'face_location' => 'getFaceLocation',
        'age_classification_confidence' => 'getAgeClassificationConfidence',
        'age_class' => 'getAgeClass',
        'age' => 'getAge',
        'gender_classification' => 'getGenderClassification',
        'gender_female_confidence' => 'getGenderFemaleConfidence',
        'gender_male_confidence' => 'getGenderMaleConfidence'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['face_location'] = isset($data['face_location']) ? $data['face_location'] : null;
        $this->container['age_classification_confidence'] = isset($data['age_classification_confidence']) ? $data['age_classification_confidence'] : null;
        $this->container['age_class'] = isset($data['age_class']) ? $data['age_class'] : null;
        $this->container['age'] = isset($data['age']) ? $data['age'] : null;
        $this->container['gender_classification'] = isset($data['gender_classification']) ? $data['gender_classification'] : null;
        $this->container['gender_female_confidence'] = isset($data['gender_female_confidence']) ? $data['gender_female_confidence'] : null;
        $this->container['gender_male_confidence'] = isset($data['gender_male_confidence']) ? $data['gender_male_confidence'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets face_location
     *
     * @return \Swagger\Client\Model\Face
     */
    public function getFaceLocation()
    {
        return $this->container['face_location'];
    }

    /**
     * Sets face_location
     *
     * @param \Swagger\Client\Model\Face $face_location Location and other information about the person's face corresponding to this age classification
     *
     * @return $this
     */
    public function setFaceLocation($face_location)
    {
        $this->container['face_location'] = $face_location;

        return $this;
    }

    /**
     * Gets age_classification_confidence
     *
     * @return double
     */
    public function getAgeClassificationConfidence()
    {
        return $this->container['age_classification_confidence'];
    }

    /**
     * Sets age_classification_confidence
     *
     * @param double $age_classification_confidence Confidence level of age classification; possible values are between 0.0 and 1.0; higher is better, with values &gt; 0.50 being high confidence results
     *
     * @return $this
     */
    public function setAgeClassificationConfidence($age_classification_confidence)
    {
        $this->container['age_classification_confidence'] = $age_classification_confidence;

        return $this;
    }

    /**
     * Gets age_class
     *
     * @return string
     */
    public function getAgeClass()
    {
        return $this->container['age_class'];
    }

    /**
     * Sets age_class
     *
     * @param string $age_class The person's age range classification result in years; possible values are \"0-2\", \"4-6\", \"8-13\", \"15-20\", \"25-32\", \"38-43\", \"48-53\", \"60+\"
     *
     * @return $this
     */
    public function setAgeClass($age_class)
    {
        $this->container['age_class'] = $age_class;

        return $this;
    }

    /**
     * Gets age
     *
     * @return double
     */
    public function getAge()
    {
        return $this->container['age'];
    }

    /**
     * Sets age
     *
     * @param double $age The specific estimated age of the person
     *
     * @return $this
     */
    public function setAge($age)
    {
        $this->container['age'] = $age;

        return $this;
    }

    /**
     * Gets gender_classification
     *
     * @return string
     */
    public function getGenderClassification()
    {
        return $this->container['gender_classification'];
    }

    /**
     * Sets gender_classification
     *
     * @param string $gender_classification Gender estimation classification as Female or Male
     *
     * @return $this
     */
    public function setGenderClassification($gender_classification)
    {
        $this->container['gender_classification'] = $gender_classification;

        return $this;
    }

    /**
     * Gets gender_female_confidence
     *
     * @return double
     */
    public function getGenderFemaleConfidence()
    {
        return $this->container['gender_female_confidence'];
    }

    /**
     * Sets gender_female_confidence
     *
     * @param double $gender_female_confidence Confidence level of classification as female; possible values are between 0.0 and 1.0
     *
     * @return $this
     */
    public function setGenderFemaleConfidence($gender_female_confidence)
    {
        $this->container['gender_female_confidence'] = $gender_female_confidence;

        return $this;
    }

    /**
     * Gets gender_male_confidence
     *
     * @return double
     */
    public function getGenderMaleConfidence()
    {
        return $this->container['gender_male_confidence'];
    }

    /**
     * Sets gender_male_confidence
     *
     * @param double $gender_male_confidence Confidence level of classification as male; possible values are between 0.0 and 1.0
     *
     * @return $this
     */
    public function setGenderMaleConfidence($gender_male_confidence)
    {
        $this->container['gender_male_confidence'] = $gender_male_confidence;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


