<?php
/**
 * DrawTextRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DrawTextRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description Request to draw one or more pieces of text onto an image
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DrawTextRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DrawTextRequest"
     */
    public function testDrawTextRequest()
    {
    }

    /**
     * Test attribute "base_image_bytes"
     */
    public function testPropertyBaseImageBytes()
    {
    }

    /**
     * Test attribute "base_image_url"
     */
    public function testPropertyBaseImageUrl()
    {
    }

    /**
     * Test attribute "text_to_draw"
     */
    public function testPropertyTextToDraw()
    {
    }
}
