<?php
/**
 * FaceMatchTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FaceMatchTest Class Doc Comment
 *
 * @category    Class
 * @description Location of one face in an image, along with match results
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FaceMatchTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FaceMatch"
     */
    public function testFaceMatch()
    {
    }

    /**
     * Test attribute "left_x"
     */
    public function testPropertyLeftX()
    {
    }

    /**
     * Test attribute "top_y"
     */
    public function testPropertyTopY()
    {
    }

    /**
     * Test attribute "right_x"
     */
    public function testPropertyRightX()
    {
    }

    /**
     * Test attribute "bottom_y"
     */
    public function testPropertyBottomY()
    {
    }

    /**
     * Test attribute "high_confidence_match"
     */
    public function testPropertyHighConfidenceMatch()
    {
    }

    /**
     * Test attribute "match_score"
     */
    public function testPropertyMatchScore()
    {
    }
}
