<?php
/**
 * FaceWithLandmarksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FaceWithLandmarksTest Class Doc Comment
 *
 * @category    Class */
// * @description Location of one face in an image
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FaceWithLandmarksTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FaceWithLandmarks"
     */
    public function testFaceWithLandmarks()
    {
    }

    /**
     * Test attribute "left_x"
     */
    public function testPropertyLeftX()
    {
    }

    /**
     * Test attribute "top_y"
     */
    public function testPropertyTopY()
    {
    }

    /**
     * Test attribute "right_x"
     */
    public function testPropertyRightX()
    {
    }

    /**
     * Test attribute "bottom_y"
     */
    public function testPropertyBottomY()
    {
    }

    /**
     * Test attribute "left_eyebrow"
     */
    public function testPropertyLeftEyebrow()
    {
    }

    /**
     * Test attribute "right_eyebrow"
     */
    public function testPropertyRightEyebrow()
    {
    }

    /**
     * Test attribute "left_eye"
     */
    public function testPropertyLeftEye()
    {
    }

    /**
     * Test attribute "right_eye"
     */
    public function testPropertyRightEye()
    {
    }

    /**
     * Test attribute "bottom_and_sides_of_face"
     */
    public function testPropertyBottomAndSidesOfFace()
    {
    }

    /**
     * Test attribute "nose_bridge"
     */
    public function testPropertyNoseBridge()
    {
    }

    /**
     * Test attribute "nose_bottom"
     */
    public function testPropertyNoseBottom()
    {
    }

    /**
     * Test attribute "lips_inner_outline"
     */
    public function testPropertyLipsInnerOutline()
    {
    }

    /**
     * Test attribute "lips_outer_outline"
     */
    public function testPropertyLipsOuterOutline()
    {
    }
}
