<?php
/**
 * FineTextItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FineTextItemTest Class Doc Comment
 *
 * @category    Class
 * @description Individual instance of text occuring in an image; one piece of text
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FineTextItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FineTextItem"
     */
    public function testFineTextItem()
    {
    }

    /**
     * Test attribute "detected_text"
     */
    public function testPropertyDetectedText()
    {
    }

    /**
     * Test attribute "top_left_x"
     */
    public function testPropertyTopLeftX()
    {
    }

    /**
     * Test attribute "top_left_y"
     */
    public function testPropertyTopLeftY()
    {
    }

    /**
     * Test attribute "top_right_x"
     */
    public function testPropertyTopRightX()
    {
    }

    /**
     * Test attribute "top_right_y"
     */
    public function testPropertyTopRightY()
    {
    }

    /**
     * Test attribute "bottom_left_x"
     */
    public function testPropertyBottomLeftX()
    {
    }

    /**
     * Test attribute "bottom_left_y"
     */
    public function testPropertyBottomLeftY()
    {
    }

    /**
     * Test attribute "bottom_right_x"
     */
    public function testPropertyBottomRightX()
    {
    }

    /**
     * Test attribute "bottom_right_y"
     */
    public function testPropertyBottomRightY()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "angle"
     */
    public function testPropertyAngle()
    {
    }
}
