<?php
/**
 * NsfwApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * NsfwApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NsfwApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for nsfwClassify
     *
     * Not safe for work (NSFW) content classification for Images.
     *
     */
    public function testNsfwClassify()
    {
    }

    /**
     * Test case for nsfwClassifyAdvanced
     *
     * Advanced content moderation and not safe for work (NSFW) content classification for Images.
     *
     */
    public function testNsfwClassifyAdvanced()
    {
    }

    /**
     * Test case for nsfwClassifyDocument
     *
     * Not safe for work (NSFW) content classification for Documents.
     *
     */
    public function testNsfwClassifyDocument()
    {
    }

    /**
     * Test case for nsfwClassifyVideo
     *
     * Not safe for work (NSFW) content classification for Video.
     *
     */
    public function testNsfwClassifyVideo()
    {
    }
}
