<?php
/**
 * RecognizeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * imageapi
 *
 * Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RecognizeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RecognizeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for recognizeDescribe
     *
     * Describe an image in natural language.
     *
     */
    public function testRecognizeDescribe()
    {
    }

    /**
     * Test case for recognizeDetectAndUnskewDocument
     *
     * Detect and unskew a photo of a document.
     *
     */
    public function testRecognizeDetectAndUnskewDocument()
    {
    }

    /**
     * Test case for recognizeDetectTextFine
     *
     * Detect fine text in a photo of a document.
     *
     */
    public function testRecognizeDetectTextFine()
    {
    }

    /**
     * Test case for recognizeDetectTextLarge
     *
     * Detect large text in a photo.
     *
     */
    public function testRecognizeDetectTextLarge()
    {
    }

    /**
     * Test case for recognizeDetectVehicleLicensePlates
     *
     * Detect vehicle license plates in an image.
     *
     */
    public function testRecognizeDetectVehicleLicensePlates()
    {
    }

    /**
     * Test case for recognizeFindSymbol
     *
     * Find the location of a symbol in an image.
     *
     */
    public function testRecognizeFindSymbol()
    {
    }

    /**
     * Test case for recognizeSimilarityCompare
     *
     * Compare two images for similarity.
     *
     */
    public function testRecognizeSimilarityCompare()
    {
    }

    /**
     * Test case for recognizeSimilarityHash
     *
     * Generate a perceptual image hash.
     *
     */
    public function testRecognizeSimilarityHash()
    {
    }

    /**
     * Test case for recognizeSimilarityHashDistance
     *
     * Calculates the similarity between two perceptual image hashes.
     *
     */
    public function testRecognizeSimilarityHashDistance()
    {
    }
}
